# Generated by Django 5.2.8 on 2025-11-08 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="tontines",
            fields=[
                (
                    "idTontines",
                    models.AutoField(
                        db_column="idTontines", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nomTontines",
                    models.CharField(db_column="nomTontines", max_length=45),
                ),
                (
                    "montantTontine",
                    models.DecimalField(
                        db_column="montantTontine", decimal_places=5, max_digits=20
                    ),
                ),
                ("libelle", models.CharField(max_length=500)),
                (
                    "Datecreation",
                    models.DateField(blank=True, db_column="dateCreation", null=True),
                ),
                (
                    "type_tontine",
                    models.CharField(
                        choices=[
                            ("S", "Tontine Spéciale Journalière"),
                            ("A", "Tontine A 2000"),
                            ("B", "Tontine B 5000"),
                            ("C", "Tontine C 10000"),
                            ("D", "Tontine D 100000"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "montant_obligatoire",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=10),
                ),
            ],
            options={
                "db_table": "tontines",
            },
        ),
        migrations.CreateModel(
            name="DemandeModification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_demande",
                    models.CharField(
                        choices=[
                            ("Tontine", "Tontine"),
                            ("Pret", "Prêt"),
                            ("Remboursement", "Remboursement"),
                            ("Epargne", "Épargne"),
                            ("Don", "Don"),
                        ],
                        max_length=20,
                    ),
                ),
                ("donnees", models.JSONField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("En attente", "En attente"),
                            ("Validée", "Validée"),
                            ("Refusée", "Refusée"),
                        ],
                        default="En attente",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="membre",
            fields=[
                (
                    "idMembre",
                    models.BigAutoField(
                        db_column="idMembre", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, db_column="nom", max_length=50, null=True
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        blank=True, db_column="prenom", max_length=50, null=True
                    ),
                ),
                (
                    "anneeNais",
                    models.SmallIntegerField(
                        blank=True, db_column="anneeNais", null=True
                    ),
                ),
                ("anneeEntree", models.SmallIntegerField(blank=True, null=True)),
                (
                    "login",
                    models.CharField(db_column="login", max_length=50, unique=True),
                ),
                ("sexe", models.CharField(max_length=1)),
                (
                    "engagement",
                    models.CharField(
                        choices=[
                            ("marie(e)", "Marie(e)"),
                            ("celibataire", "Celibataire"),
                            ("divorce(e)", "Divorce(e)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("telephone1", models.CharField(blank=True, max_length=15, null=True)),
                ("telephone2", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=50, null=True)),
                ("actif", models.IntegerField(blank=True, null=True)),
                ("photo", models.CharField(blank=True, max_length=50, null=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membre",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "membre",
            },
        ),
        migrations.CreateModel(
            name="epargne",
            fields=[
                (
                    "idEpargne",
                    models.AutoField(
                        db_column="idEpargne", primary_key=True, serialize=False
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "modeVersement",
                    models.CharField(db_column="modeVersement", max_length=20),
                ),
                (
                    "couponVersement",
                    models.CharField(
                        blank=True,
                        db_column="couponVersement",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("idSeance", models.BigIntegerField(db_column="idSeance")),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "idMembre",
                    models.ForeignKey(
                        db_column="idMembre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epargnes",
                        to="Association_tontine.membre",
                    ),
                ),
            ],
            options={
                "db_table": "epargne",
            },
        ),
        migrations.CreateModel(
            name="aide",
            fields=[
                (
                    "numAide",
                    models.AutoField(
                        db_column="numAide", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(blank=True, db_column="date", null=True)),
                (
                    "motif_aide",
                    models.CharField(
                        blank=True, db_column="motif_aide", max_length=50, null=True
                    ),
                ),
                (
                    "montantAide",
                    models.DecimalField(
                        db_column="montantAide", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "nomBeneficiaire",
                    models.CharField(db_column="nomBeneficiaire", max_length=50),
                ),
                (
                    "lienBeneficiareAvecMembre",
                    models.CharField(
                        db_column="lienBeneficiareAvecMembre", max_length=50
                    ),
                ),
                (
                    "type_aide",
                    models.CharField(
                        blank=True, db_column="type_aide", max_length=50, null=True
                    ),
                ),
                (
                    "lieu",
                    models.CharField(
                        blank=True, db_column="lieu", max_length=255, null=True
                    ),
                ),
                (
                    "idMembre",
                    models.ForeignKey(
                        db_column="idMembre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aides",
                        to="Association_tontine.membre",
                    ),
                ),
            ],
            options={
                "db_table": "aide",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_modification", models.CharField(max_length=100)),
                ("details", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En Attente"),
                            ("valide", "Validé"),
                            ("refuse", "Refusé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="pret",
            fields=[
                (
                    "idpret",
                    models.BigAutoField(
                        db_column="idpret", primary_key=True, serialize=False
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                ("observations", models.TextField(blank=True, null=True)),
                ("date_demande", models.DateTimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[("en_cours", "En Cours"), ("rembourse", "Remboursé")],
                        max_length=50,
                    ),
                ),
                ("pourcentage", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "cni_avaliste",
                    models.FileField(blank=True, null=True, upload_to="documents_cni/"),
                ),
                (
                    "idSeance",
                    models.BigIntegerField(blank=True, db_column="idSeance", null=True),
                ),
                (
                    "idSeance_1",
                    models.BigIntegerField(
                        blank=True, db_column="idSeance_1", null=True
                    ),
                ),
                ("est_rembourse", models.BooleanField(default=False)),
                (
                    "idMembre_avaliste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prets_avaliste",
                        to="Association_tontine.membre",
                    ),
                ),
                (
                    "idMembre_preteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prets_preteur",
                        to="Association_tontine.membre",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pret",
            },
        ),
        migrations.CreateModel(
            name="remboursement",
            fields=[
                (
                    "idRembo",
                    models.BigAutoField(
                        db_column="idRembo", primary_key=True, serialize=False
                    ),
                ),
                (
                    "montant_rembourse",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("date_remboursement", models.DateTimeField()),
                ("idSeance", models.BigIntegerField(db_column="idSeance")),
                (
                    "idMembre",
                    models.ForeignKey(
                        db_column="idMembre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remboursements",
                        to="Association_tontine.membre",
                    ),
                ),
                (
                    "idpret",
                    models.ForeignKey(
                        db_column="idpret",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remboursements",
                        to="Association_tontine.pret",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "remboursement",
            },
        ),
        migrations.CreateModel(
            name="sanction",
            fields=[
                (
                    "idSanction",
                    models.AutoField(
                        db_column="idSanction", primary_key=True, serialize=False
                    ),
                ),
                ("dateSanction", models.DateField(db_column="dateSanction")),
                (
                    "typeSanction",
                    models.CharField(db_column="typeSanction", max_length=50),
                ),
                (
                    "montant",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("raison", models.TextField()),
                (
                    "idMembre",
                    models.ForeignKey(
                        db_column="idMembre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sanctions",
                        to="Association_tontine.membre",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sanction",
            },
        ),
        migrations.CreateModel(
            name="don",
            fields=[
                (
                    "iddon",
                    models.AutoField(
                        db_column="iddon", primary_key=True, serialize=False
                    ),
                ),
                ("nature_don", models.CharField(max_length=255)),
                ("date_don", models.DateField()),
                ("montant_don", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description_don", models.CharField(max_length=255)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "idMembre",
                    models.ForeignKey(
                        db_column="idMembre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dons",
                        to="Association_tontine.membre",
                    ),
                ),
                (
                    "idTontines",
                    models.ForeignKey(
                        db_column="idTontines",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Association_tontine.tontines",
                    ),
                ),
            ],
            options={
                "db_table": "don",
            },
        ),
        migrations.CreateModel(
            name="cotisation",
            fields=[
                (
                    "codeCotisation",
                    models.BigAutoField(
                        db_column="codeCotisation", primary_key=True, serialize=False
                    ),
                ),
                ("libelle", models.CharField(max_length=15)),
                ("montant", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "date_paiement",
                    models.DateField(blank=True, db_column="date_paiement"),
                ),
                ("est_valide", models.BooleanField(default=False)),
                (
                    "nbPartMax",
                    models.IntegerField(blank=True, db_column="nbPartMax", null=True),
                ),
                (
                    "penaliteDefaillanceBenef",
                    models.DecimalField(
                        blank=True,
                        db_column="penaliteDefaillanceBenef",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "penaliteDefaillanceNonBenef",
                    models.DecimalField(
                        blank=True,
                        db_column="penaliteDefaillanceNonBenef",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "miseAPrix",
                    models.DecimalField(
                        db_column="miseAPrix", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "idMembre",
                    models.ForeignKey(
                        db_column="idMembre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotisations",
                        to="Association_tontine.membre",
                    ),
                ),
                (
                    "tontine",
                    models.ForeignKey(
                        db_column="tontines",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Association_tontine.tontines",
                    ),
                ),
            ],
            options={
                "db_table": "cotisation",
            },
        ),
        migrations.CreateModel(
            name="TontinesMembres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_entree", models.DateField(auto_now_add=True, null=True)),
                ("numero_adhesion", models.PositiveIntegerField()),
                (
                    "membres",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Association_tontine.membre",
                    ),
                ),
                (
                    "tontines",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Association_tontine.tontines",
                    ),
                ),
            ],
            options={
                "db_table": "tontines_membres",
            },
        ),
        migrations.AddField(
            model_name="tontines",
            name="membres",
            field=models.ManyToManyField(
                related_name="tontines",
                through="Association_tontine.TontinesMembres",
                to="Association_tontine.membre",
            ),
        ),
        migrations.CreateModel(
            name="versementcotis",
            fields=[
                (
                    "idVersCotis",
                    models.AutoField(
                        db_column="idVersCotis", primary_key=True, serialize=False
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "modeVersement",
                    models.CharField(db_column="modeVersement", max_length=20),
                ),
                (
                    "couponVersement",
                    models.CharField(
                        blank=True,
                        db_column="couponVersement",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("idSeance", models.BigIntegerField(db_column="idSeance")),
                (
                    "codeCotisation",
                    models.ForeignKey(
                        db_column="codeCotisation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versementcotisa",
                        to="Association_tontine.cotisation",
                    ),
                ),
                (
                    "idMembre",
                    models.ForeignKey(
                        db_column="idMembre",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Association_tontine.membre",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "versementcotis",
            },
        ),
        migrations.CreateModel(
            name="versementsol",
            fields=[
                (
                    "idVersSol",
                    models.AutoField(
                        db_column="idVersSol", primary_key=True, serialize=False
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "modeVersement",
                    models.CharField(db_column="modeVersement", max_length=20),
                ),
                (
                    "couponVersement",
                    models.CharField(
                        blank=True,
                        db_column="couponVersement",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("idSeance", models.BigIntegerField(db_column="idSeance")),
                (
                    "idMembre",
                    models.ForeignKey(
                        db_column="idMembre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versementsols",
                        to="Association_tontine.membre",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "versementSol",
            },
        ),
    ]
