# Generated by Django 5.2.8 on 2025-12-25 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Association_tontine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="utilisateur",
        ),
        migrations.CreateModel(
            name="Demande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_demande",
                    models.CharField(
                        choices=[
                            ("TONTINE", "Adhésion Tontine"),
                            ("PRET", "Demande de Prêt"),
                            ("REMBOURSEMENT", "Déclaration de Remboursement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("donnees", models.JSONField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En Attente"),
                            ("VALIDEE", "Validée"),
                            ("REFUSEE", "Refusée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                ("commentaire_admin", models.TextField(blank=True, null=True)),
                (
                    "traitee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_traitees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
        migrations.DeleteModel(
            name="DemandeModification",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
