# Generated by Django 5.2.8 on 2026-01-09 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Association_tontine",
            "0002_remove_notification_utilisateur_demande_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeModification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_demande",
                    models.CharField(
                        choices=[
                            ("Tontine", "Tontine"),
                            ("Pret", "Prêt"),
                            ("Remboursement", "Remboursement"),
                            ("Epargne", "Épargne"),
                            ("Don", "Don"),
                        ],
                        max_length=20,
                    ),
                ),
                ("donnees", models.JSONField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("En attente", "En attente"),
                            ("Validée", "Validée"),
                            ("Refusée", "Refusée"),
                        ],
                        default="En attente",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_modification", models.CharField(max_length=100)),
                ("details", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En Attente"),
                            ("valide", "Validé"),
                            ("refuse", "Refusé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Demande",
        ),
    ]
